export const IDENTITY_ERROR_IDENTIFIER = {
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',

  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
} as const;
