export const IDENTITY_ERROR_IDENTIFIER = {
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',

  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
} as const;
